
WebExcess:
  BaseTypes:
    Button:
      className: btn
    Image:
      maxWidth: 2560
      maxHeight: 1440
      cropping: false
      upScaling: false
Neos:
  Neos:
    typoScript:
      autoInclude:
        WebExcess.BaseTypes: true
    userInterface:
      translation:
        autoInclude:
          WebExcess.BaseTypes:
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        basetypes:
          label: 'Base Types'
          position: 10
          collapsed: false
        themetypes:
          label: 'Theme Types'
          position: 20
          collapsed: false
        general:
          position: 50
          collapsed: false
        structure:
          collapsed: true
